### ISSUE TITLE
Unable to run more than once on Manjaro

### ISSUE THREAD

**Issue by Lillievela** [z80z80z80/MarikoDoom#1]
As the title states, I cannot seem to get it to run more than once on my manjaro install. Im not entirely sure what is causing it but after closing the previous process it gives me a netlink error stating it cannot run it

**Comment by z80z80z80** [comment]
It's possible that not all processes have been closed.  This software contains of 3 major parts: the VizDoom instance, the http server and the access point. 

VizDoom is the main process that is controlling the other parts as threads. When it is closed via keyboard interrupt it should close all other threads and everything should be fine for another run. Though if you stop the process with i.e. a `kill` command this might not be the case. 

Try this:
- `ps ax | grep http_server.py` (this should show you the PID of the http server if it is still running)
- `kill -9 [PID]` (to stop that server)
- `create_ap --list-running` (to list all access point instances)
- `create_ap --stop apX` (to kill an access point with the name apX, repeat that for all of them)

After this it should run normally:
`sudo python run.py --ap YOUR_INTERFACE`

Let me know if this worked.

**Comment by Lillievela** [comment]
I have tried but the first apX (ap0 in my case) does not seem to close, i did manage to kill it and all python/vizdoom in ksysguard though

**Comment by z80z80z80** [comment]
Is there any error message when trying to stop ap0?

**Comment by Lillievela** [comment]
It just says its trying to close the process but it doesnt end up doing anything

**Comment by z80z80z80** [comment]
Weird. So, after doing what you did: is ap0 still showing up when you execute `ip address`?

Also, does it run as normal after you restart your system?

**Comment by Lillievela** [comment]
It does still show up, and it works just fine after a reboot

**Comment by Lillievela** [comment]
Alright so i had noticed that the sound wasnt working, so i looked through it using `ps -fA | grep python` and closed out everything. So it looks like for me i need to run the mentioned command, close out of whatever is there thats from the server, check the apX and then close out of whatever is there. Seems like i just wasnt closing the right stuff or something. But its now letting me re-run it, just a matter of which i close and checking
